// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrbanGarden.Api.Data;

#nullable disable

namespace urban_garden_api.Migrations
{
    [DbContext(typeof(UrbanGardenDbContext))]
    [Migration("20260720115521_FixDevice")]
    partial class FixDevice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrbanGarden.Api.Models.Entities.CropType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPerennial")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("Season")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("ID");

                    b.ToTable("CropTypes");
                });

            modelBuilder.Entity("UrbanGarden.Api.Models.Entities.Device", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GardenPlotId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("GardenPlotId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("UrbanGarden.Api.Models.Entities.GardenPlot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Size")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.ToTable("GardenPlots");
                });

            modelBuilder.Entity("UrbanGarden.Api.Models.Entities.Harvest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlantedCropId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PlantedCropId");

                    b.ToTable("Harvests");
                });

            modelBuilder.Entity("UrbanGarden.Api.Models.Entities.PlantedCrop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CropTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("GardenPlotId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CropTypeId");

                    b.HasIndex("GardenPlotId");

                    b.ToTable("PlantedCrops");
                });

            modelBuilder.Entity("UrbanGarden.Api.Models.Entities.SoilSensorReadings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<Guid>("DeviceID")
                        .HasColumnType("uuid");

                    b.Property<double>("Moisture")
                        .HasColumnType("double precision");

                    b.Property<int>("SensorIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("DeviceID");

                    b.ToTable("SoilSensorReadings");
                });

            modelBuilder.Entity("UrbanGarden.Api.Models.Entities.TemperatureSensorReadings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<Guid>("DeviceID")
                        .HasColumnType("uuid");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("DeviceID");

                    b.ToTable("TemperatureSensorReadings");
                });

            modelBuilder.Entity("UrbanGarden.Api.Models.Entities.Device", b =>
                {
                    b.HasOne("UrbanGarden.Api.Models.Entities.GardenPlot", "GardenPlot")
                        .WithMany("Devices")
                        .HasForeignKey("GardenPlotId");

                    b.Navigation("GardenPlot");
                });

            modelBuilder.Entity("UrbanGarden.Api.Models.Entities.GardenPlot", b =>
                {
                    b.OwnsOne("UrbanGarden.Api.Models.Entities.Direction", "Location", b1 =>
                        {
                            b1.Property<int>("GardenPlotID")
                                .HasColumnType("integer");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("GardenPlotID");

                            b1.ToTable("GardenPlots");

                            b1.WithOwner()
                                .HasForeignKey("GardenPlotID");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("UrbanGarden.Api.Models.Entities.Harvest", b =>
                {
                    b.HasOne("UrbanGarden.Api.Models.Entities.PlantedCrop", "PlantedCrop")
                        .WithMany("Harvests")
                        .HasForeignKey("PlantedCropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantedCrop");
                });

            modelBuilder.Entity("UrbanGarden.Api.Models.Entities.PlantedCrop", b =>
                {
                    b.HasOne("UrbanGarden.Api.Models.Entities.CropType", "CropType")
                        .WithMany("PlantedCrops")
                        .HasForeignKey("CropTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanGarden.Api.Models.Entities.GardenPlot", "GardenPlot")
                        .WithMany("PlantedCrops")
                        .HasForeignKey("GardenPlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CropType");

                    b.Navigation("GardenPlot");
                });

            modelBuilder.Entity("UrbanGarden.Api.Models.Entities.SoilSensorReadings", b =>
                {
                    b.HasOne("UrbanGarden.Api.Models.Entities.Device", "Device")
                        .WithMany("SoilReadings")
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("UrbanGarden.Api.Models.Entities.TemperatureSensorReadings", b =>
                {
                    b.HasOne("UrbanGarden.Api.Models.Entities.Device", "Device")
                        .WithMany("TemperatureReadings")
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("UrbanGarden.Api.Models.Entities.CropType", b =>
                {
                    b.Navigation("PlantedCrops");
                });

            modelBuilder.Entity("UrbanGarden.Api.Models.Entities.Device", b =>
                {
                    b.Navigation("SoilReadings");

                    b.Navigation("TemperatureReadings");
                });

            modelBuilder.Entity("UrbanGarden.Api.Models.Entities.GardenPlot", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("PlantedCrops");
                });

            modelBuilder.Entity("UrbanGarden.Api.Models.Entities.PlantedCrop", b =>
                {
                    b.Navigation("Harvests");
                });
#pragma warning restore 612, 618
        }
    }
}
